[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "CFSDS"
authors = [{name = "NRCan - Quinn Barber", email = "graziella@lumache"}]
dynamic = ["version", "description"]
